import type { Metadata } from "next";
import { NextAuthProvider } from "./lib/next-auth/provider";
// import { Geist, Geist_Mono } from "next/font/google";
import { Noto_Sans_JP } from "next/font/google";
import { Suspense } from "react";
import Header from "./components/Header";
import "./globals.css";
import Loading from "./Loading";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "My Book Commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansJP.className} antialiased`}>
        <NextAuthProvider>
          <Header />
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </NextAuthProvider>
      </body>
    </html>
  );
}
